title:  Salam! I am Mehmet Eray Avcı.
description: I designed this website to publish my academic CV and papers.
theme: just-the-docs

url: https://erayvci.github.io/academic-cv/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
